server.port: 8443
server.ssl.bundle: server
spring.profiles.active: dev

---
spring.config.activate.on-profile: dev
server.port: 8444
client.url: https://localhost:8443/callme
spring.ssl.bundle.jks:
  server:
    reload-on-update: true
    keystore:
      location: classpath:keystore.jks
      password: 123456
      type: JKS
  client:
    reload-on-update: true
    truststore:
      location: classpath:truststore2.jks
      password: 123456
      type: JKS
---
spring.config.activate.on-profile: prod
client.url: https://${HOST}:8443/callme
spring.ssl.bundle.jks:
  server:
    reload-on-update: true
    keystore:
      location: ${CERT_PATH}/keystore.jks
      password: ${PASSWORD}
      type: JKS
  client:
    reload-on-update: true
    truststore:
      location: ${CLIENT_CERT_PATH}/keystore.jks
      password: ${PASSWORD}
      type: JKS